Repository bitwarden/server, pull requests merged in 2021-01, with the labels that each got.

#1057 Implemented Custom role and permissions
  bitwarden_license/src/Portal/Controllers/PoliciesController.cs
  bitwarden_license/src/Portal/Controllers/SsoController.cs
  bitwarden_license/src/Portal/EnterprisePortalCurrentContext.cs
  bitwarden_license/src/Portal/Views/Home/Index.cshtml
  bitwarden_license/src/Portal/Views/Shared/_Layout.cshtml
  src/Api/Controllers/CiphersController.cs
  src/Api/Controllers/CollectionsController.cs
  src/Api/Controllers/EventsController.cs
  src/Api/Controllers/GroupsController.cs
  src/Api/Controllers/OrganizationUsersController.cs
  src/Api/Controllers/PoliciesController.cs
  src/Api/Controllers/TwoFactorController.cs
  src/Api/Public/Controllers/MembersController.cs
  src/Core/CurrentContext.cs
  src/Core/Enums/OrganizationUserType.cs
  src/Core/IdentityServer/ApiResources.cs
  src/Core/Models/Api/Request/Organizations/OrganizationUpdateRequestModel.cs
  src/Core/Models/Api/Request/Organizations/OrganizationUserRequestModels.cs
  src/Core/Models/Api/Response/OrganizationUserResponseModel.cs
  src/Core/Models/Api/Response/ProfileOrganizationResponseModel.cs
  src/Core/Models/Business/OrganizationUserInvite.cs
  src/Core/Models/Data/OrganizationUserOrganizationDetails.cs
  src/Core/Models/Data/OrganizationUserUserDetails.cs
  src/Core/Models/Data/Permissions.cs
  src/Core/Models/Table/OrganizationUser.cs
  src/Core/Services/IOrganizationService.cs
  src/Core/Services/Implementations/OrganizationService.cs
  src/Core/Utilities/CoreHelpers.cs
  src/Sql/dbo/Stored Procedures/OrganizationUser_Create.sql
  src/Sql/dbo/Stored Procedures/OrganizationUser_CreateWithCollections.sql
  src/Sql/dbo/Stored Procedures/OrganizationUser_Update.sql
  src/Sql/dbo/Stored Procedures/OrganizationUser_UpdateWithCollections.sql
  src/Sql/dbo/Tables/OrganizationUser.sql
  src/Sql/dbo/Views/OrganizationUserOrganizationDetailsView.sql
  src/Sql/dbo/Views/OrganizationUserUserDetailsView.sql
  test/Core.Test/AutoFixture/CipherFixtures.cs
  test/Core.Test/AutoFixture/OrganizationFixtures.cs
  test/Core.Test/Services/OrganizationServiceTests.cs
  util/Migrator/DbScripts/2020-12-14_00_Permissions.sql
Labels: enhancement

#1076 [Policy] Update Personal Ownership checkbox description
  bitwarden_license/src/Portal/Models/PolicyEditModel.cs
  bitwarden_license/src/Portal/Models/PolicyModel.cs
  bitwarden_license/src/Portal/Views/Policies/Edit.cshtml
  src/Core/Resources/SharedResources.en.resx
Labels: enhancement

#1092 [Email] Update welcome content
  src/Core/MailTemplates/Handlebars/Layouts/Full.html.hbs
  src/Core/MailTemplates/Handlebars/Layouts/Full.text.hbs
  src/Core/MailTemplates/Handlebars/Welcome.html.hbs
  src/Core/MailTemplates/Handlebars/Welcome.text.hbs
  src/Core/Models/Mail/BaseMailModel.cs
  src/Core/Services/Implementations/HandlebarsMailService.cs
Labels: enhancement, hold

#1106 Send Sync Notifications
  src/Api/Controllers/SendsController.cs
  src/Core/Enums/PushType.cs
  src/Core/Models/PushNotification.cs
  src/Core/Services/IPushNotificationService.cs
  src/Core/Services/Implementations/AzureQueuePushNotificationService.cs
  src/Core/Services/Implementations/MultiServicePushNotificationService.cs
  src/Core/Services/Implementations/NotificationHubPushNotificationService.cs
  src/Core/Services/Implementations/NotificationsApiPushNotificationService.cs
  src/Core/Services/Implementations/RelayPushNotificationService.cs
  src/Core/Services/Implementations/SendService.cs
  src/Core/Services/NoopImplementations/NoopPushNotificationService.cs
  src/Notifications/HubHelpers.cs
Labels: enhancement

#1114 self-hosted version bump v1.39.3
  scripts/bitwarden.ps1
  scripts/bitwarden.sh
Labels: hold
