Repository bitwarden/server, pull requests merged in 2022-12, with the labels that each got.

#2476 [PS-1992] Updating broken link to Server Setup Guide
  README.md
Labels: community-pr

#2455 [SG-661] Background Domain Verification Service
  src/Api/Jobs/JobsHostedService.cs
  src/Api/Jobs/ValidateOrganizationDomainJob.cs
  src/Core/Entities/OrganizationDomain.cs
  src/Core/Repositories/IOrganizationDomainRepository.cs
  src/Core/Services/IVerificationDomainService.cs
  src/Core/Services/Implementations/VerificationDomainService.cs
  src/Infrastructure.Dapper/Repositories/OrganizationDomainRepository.cs
  src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs
  src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
  src/Sql/Sql.sqlproj
  src/Sql/dbo/Stored Procedures/OrganizationDomain_ReadByNextRunDate.sql
  util/Migrator/DbScripts/2022-11-24_00_OrganizationDomainCheckUnverifiedDomains.sql
Labels: DB-migrations-changed

#2342 [PS-1675] Fix bug #2317: add deletion date validation for File Sends
  src/Api/Controllers/SendsController.cs
  test/Api.Test/Controllers/SendsControllerTests.cs
Labels: community-pr

#2501 [SG-841] Fixed null issue when an organization key does not exist
  src/Core/OrganizationFeatures/OrganizationApiKeys/GetOrganizationApiKeyQuery.cs
Labels: bug

#2520 add support for BW_DB_PORT
  docker-unified/entrypoint.sh
Labels: bw-unified-deploy

#2517 [SG-911] Added Configurable Days
  src/Core/Entities/OrganizationDomain.cs
  src/Core/OrganizationFeatures/OrganizationDomains/CreateOrganizationDomainCommand.cs
  src/Core/Repositories/IOrganizationDomainRepository.cs
  src/Core/Services/Implementations/OrganizationDomainService.cs
  src/Core/Settings/GlobalSettings.cs
  src/Core/Settings/IDomainVerificationSettings.cs
  src/Core/Settings/IGlobalSettings.cs
  src/Infrastructure.Dapper/Repositories/OrganizationDomainRepository.cs
  src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs
  src/Sql/dbo/Stored Procedures/OrganizationDomain_DeleteIfExpired.sql
  util/Migrator/DbScripts/2022-11-03_00_OrganizationDomainInit.sql
Labels: DB-migrations-changed
