Repository bitwarden/server, pull requests merged in 2023-01, with the labels that each got.

#2523 [PS-2136] Fix Inactive two-step login check
  docker-unified/hbs/nginx-config.hbs
  util/Setup/Configuration.cs
Labels: community-pr

#2512 [PS-2099] PostgreSQL EF Contains() in SQL Query is strpos(), witch is case-sens…
  src/Infrastructure.EntityFramework/Repositories/Queries/CipherDetailsQuery.cs
  src/Infrastructure.EntityFramework/Repositories/Queries/UserCipherDetailsQuery.cs
Labels: community-pr, bw-unified-deploy

#2602 [SG-957] Cannot Delete Organizations due to FK Constraint
  src/Sql/Sql.sqlproj
  src/Sql/dbo/Stored Procedures/OrganizationDomain_OrganizationDeleted.sql
  src/Sql/dbo/Stored Procedures/Organization_DeleteById.sql
  util/Migrator/DbScripts/2023_01_18_00_FixOrganizationDeleteOrgDomain.sql
Labels: bug

#2572 [PS-2242] Quotes break adminSettings__admins
  docker-unified/settings.env
Labels: community-pr, bw-unified-deploy

#2645 [SG-1009] Users with Custom Role and "Manage SSO" permission don't receive verification failed email
  src/Core/Models/Data/Organizations/OrganizationUsers/OrganizationUserUserDetails.cs
  src/Core/Services/Implementations/OrganizationDomainService.cs
  src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs
  src/Sql/dbo/Stored Procedures/OrganizationDomain_ReadIfExpired.sql
  util/Migrator/DbScripts/2022-11-03_00_OrganizationDomainInit.sql
Labels: bug, DB-migrations-changed
