Repository bitwarden/server, pull requests merged in 2023-04, with the labels that each got.

#2830 [AC-1255] Search Existing Organizations by partial Email
  src/Infrastructure.EntityFramework/Repositories/OrganizationRepository.cs
  src/Sql/dbo/Stored Procedures/Organization_UnassignedToProviderSearch.sql
  util/Migrator/DbScripts/2023-03-22_00_ProviderAddExistingOrganizations.sql
Labels: DB-migrations-changed, needs-qa

#2840 [AC-432] Checking that an existing Organization is not assigned to any Provider before being assigned
  bitwarden_license/src/Commercial.Core/Services/ProviderService.cs
  bitwarden_license/test/Commercial.Core.Test/Services/ProviderServiceTests.cs
  src/Core/Repositories/IProviderOrganizationRepository.cs
  src/Infrastructure.Dapper/Repositories/ProviderOrganizationRepository.cs
  src/Infrastructure.EntityFramework/Repositories/ProviderOrganizationRepository.cs
  src/Infrastructure.EntityFramework/Repositories/Queries/ProviderOrganizationCountByOrganizationIdsQuery.cs
  src/Sql/Sql.sqlproj
  src/Sql/dbo/Stored Procedures/ProviderOrganization_ReadCountByOrganizationIds.sql
  util/Migrator/DbScripts/2023-03-22_00_ProviderAddExistingOrganizations.sql
Labels: DB-migrations-changed

#2855 Modified Cipher_UpdateWithCollections Stored Procedure
  src/Infrastructure.EntityFramework/Vault/Repositories/CipherRepository.cs
  src/Sql/Vault/dbo/Stored Procedures/Cipher/Cipher_UpdateWithCollections.sql
  util/Migrator/DbScripts/2023-03-07_00_CipherKeyUpdate.sql
Labels: DB-migrations-changed

#2861 [PM-1876] fix: link to web releases
  src/Admin/Views/Home/Index.cshtml
Labels: community-pr
