Repository bitwarden/server, pull requests merged in 2024-04, with the labels that each got.

#3940 [AC-2350] - FIX - Add DNS TXT record generation
  src/Api/AdminConsole/Controllers/OrganizationDomainController.cs
  src/Api/AdminConsole/Models/Request/OrganizationDomainRequestModel.cs
  src/Core/AdminConsole/OrganizationFeatures/OrganizationDomains/CreateOrganizationDomainCommand.cs
  test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationDomains/CreateOrganizationDomainCommandTests.cs
Labels: bug

#3973 [AC-1218] Add ability to delete Provider Portals
  bitwarden_license/src/Commercial.Core/AdminConsole/Services/ProviderService.cs
  bitwarden_license/test/Commercial.Core.Test/AdminConsole/Services/ProviderServiceTests.cs
  src/Admin/AdminConsole/Controllers/ProvidersController.cs
  src/Admin/AdminConsole/Views/Providers/Edit.cshtml
  src/Admin/AdminConsole/Views/Providers/_ProviderScripts.cshtml
  src/Api/AdminConsole/Controllers/ProvidersController.cs
  src/Api/AdminConsole/Models/Request/Providers/ProviderVerifyDeleteRecoverRequestModel.cs
  src/Core/AdminConsole/Models/Business/Tokenables/ProviderDeleteTokenable.cs
  src/Core/AdminConsole/Services/IProviderService.cs
  src/Core/AdminConsole/Services/NoopImplementations/NoopProviderService.cs
  src/Core/Constants.cs
  src/Core/Enums/ApplicationCacheMessageType.cs
  src/Core/MailTemplates/Handlebars/Provider/InitiateDeleteProvider.html.hbs
  src/Core/MailTemplates/Handlebars/Provider/InitiateDeleteProvider.text.hbs
  src/Core/Models/Mail/Provider/ProviderInitiateDeleteModel.cs
  src/Core/Services/IApplicationCacheService.cs
  src/Core/Services/IMailService.cs
  src/Core/Services/Implementations/HandlebarsMailService.cs
  src/Core/Services/Implementations/InMemoryApplicationCacheService.cs
  src/Core/Services/Implementations/InMemoryServiceBusApplicationCacheService.cs
  src/Core/Services/NoopImplementations/NoopMailService.cs
  src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
Labels: feature-flag

#3917 [PM-6977] Migrate to FCM v1
  src/Core/Constants.cs
  src/Core/Services/Implementations/NotificationHubPushRegistrationService.cs
  test/Core.Test/Services/NotificationHubPushRegistrationServiceTests.cs
Labels: feature-flag

#4009 Revert "[PM-6977] Migrate to FCM v1 (#3917)"
  src/Core/Constants.cs
  src/Core/Services/Implementations/NotificationHubPushRegistrationService.cs
  test/Core.Test/Services/NotificationHubPushRegistrationServiceTests.cs
Labels: feature-flag

#4014 [AC-2488] Add billing endpoint to determine SM standalone for organization
  src/Api/Billing/Controllers/OrganizationBillingController.cs
  src/Api/Billing/Models/Responses/OrganizationMetadataResponse.cs
  src/Core/Billing/Constants/StripeConstants.cs
  src/Core/Billing/Extensions/ServiceCollectionExtensions.cs
  src/Core/Billing/Models/OrganizationMetadataDTO.cs
  src/Core/Billing/Queries/IOrganizationBillingQueries.cs
  src/Core/Billing/Queries/Implementations/OrganizationBillingQueries.cs
  test/Api.Test/Billing/Controllers/OrganizationBillingControllerTests.cs
  test/Core.Test/Billing/Queries/OrganizationBillingQueriesTests.cs
Labels: needs-qa

#4033 [PM-1449] Add email-verification flag
  src/Core/Constants.cs
Labels: feature-flag
