Repository bitwarden/server, pull requests merged in 2024-12, with the labels that each got.

#5093 [PM-10319] Fixing migration script
  util/Migrator/DbScripts/2024-11-26-00_OrgUserSetStatusBulk.sql
Labels: DB-migrations-changed

#5106 [PM-9111] Add `PM9111ExtensionPersistAddEditForm` feature flag
  src/Core/Constants.cs
Labels: feature-flag

#5112 Add TOTP Inline Menu feature flag
  src/Core/Constants.cs
Labels: feature-flag

#5002 [PM-11516] Initial license file refactor
  src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
  src/Core/Billing/Extensions/ServiceCollectionExtensions.cs
  src/Core/Billing/Licenses/Extensions/LicenseExtensions.cs
  src/Core/Billing/Licenses/Extensions/LicenseServiceCollectionExtensions.cs
  src/Core/Billing/Licenses/LicenseConstants.cs
  src/Core/Billing/Licenses/Models/LicenseContext.cs
  src/Core/Billing/Licenses/Services/ILicenseClaimsFactory.cs
  src/Core/Billing/Licenses/Services/Implementations/OrganizationLicenseClaimsFactory.cs
  src/Core/Billing/Licenses/Services/Implementations/UserLicenseClaimsFactory.cs
  src/Core/Constants.cs
  src/Core/Models/Business/ILicense.cs
  src/Core/Models/Business/OrganizationLicense.cs
  src/Core/Models/Business/UserLicense.cs
  src/Core/OrganizationFeatures/OrganizationLicenses/Cloud/CloudGetOrganizationLicenseQuery.cs
  src/Core/OrganizationFeatures/OrganizationLicenses/UpdateOrganizationLicenseCommand.cs
  src/Core/Services/ILicensingService.cs
  src/Core/Services/Implementations/LicensingService.cs
  src/Core/Services/Implementations/UserService.cs
  src/Core/Services/NoopImplementations/NoopLicensingService.cs
  src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
  test/Core.Test/Models/Business/OrganizationLicenseTests.cs
  test/Core.Test/OrganizationFeatures/OrganizationLicenses/UpdateOrganizationLicenseCommandTests.cs
  test/Core.Test/Services/UserServiceTests.cs
Labels: feature-flag

#5051 [PM-11360] Remove export permission for providers
  src/Api/Tools/Authorization/VaultExportAuthorizationHandler.cs
  src/Api/Tools/Authorization/VaultExportOperations.cs
  src/Api/Tools/Controllers/OrganizationExportController.cs
  src/Api/Tools/Models/Response/OrganizationExportResponseModel.cs
  src/Api/Utilities/ServiceCollectionExtensions.cs
  src/Api/Vault/Models/Response/CipherResponseModel.cs
  src/Core/Constants.cs
  src/Core/Vault/Queries/IOrganizationCiphersQuery.cs
  src/Core/Vault/Queries/OrganizationCiphersQuery.cs
  test/Api.Test/Tools/Authorization/VaultExportAuthorizationHandlerTests.cs
  test/Core.Test/AdminConsole/Helpers/AuthorizationHelpers.cs
  test/Core.Test/AdminConsole/Helpers/AuthorizationHelpersTests.cs
  test/Core.Test/Vault/Queries/OrganizationCiphersQueryTests.cs
Labels: feature-flag

#4809 Remove `LimitCollectionCreationDeletionSplit` feature flag
  src/Admin/AdminConsole/Views/Organizations/_ViewInformation.cshtml
  src/Api/AdminConsole/Controllers/OrganizationsController.cs
  src/Api/AdminConsole/Models/Response/Organizations/OrganizationResponseModel.cs
  src/Api/AdminConsole/Models/Response/ProfileOrganizationResponseModel.cs
  src/Api/AdminConsole/Models/Response/ProfileProviderOrganizationResponseModel.cs
  src/Api/Models/Request/Organizations/OrganizationCollectionManagementUpdateRequestModel.cs
  src/Api/Vault/AuthorizationHandlers/Collections/BulkCollectionAuthorizationHandler.cs
  src/Core/AdminConsole/Entities/Organization.cs
  src/Core/AdminConsole/Models/Data/Organizations/OrganizationAbility.cs
  src/Core/AdminConsole/Models/Data/Organizations/OrganizationUsers/OrganizationUserOrganizationDetails.cs
  src/Core/AdminConsole/Models/Data/Organizations/SelfHostedOrganizationDetails.cs
  src/Core/AdminConsole/Models/Data/Provider/ProviderUserOrganizationDetails.cs
  src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
  src/Core/Billing/Licenses/Services/Implementations/OrganizationLicenseClaimsFactory.cs
  src/Core/Constants.cs
  src/Core/Models/Business/OrganizationLicense.cs
  src/Infrastructure.EntityFramework/AdminConsole/Models/Organization.cs
  src/Infrastructure.EntityFramework/AdminConsole/Repositories/OrganizationRepository.cs
  src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/OrganizationUserOrganizationDetailsViewQuery.cs
  src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/ProviderUserOrganizationDetailsViewQuery.cs
  test/Api.Test/Vault/AuthorizationHandlers/BulkCollectionAuthorizationHandlerTests.cs
  test/Core.Test/Models/Business/OrganizationLicenseFileFixtures.cs
  test/Core.Test/OrganizationFeatures/OrganizationLicenses/UpdateOrganizationLicenseCommandTests.cs
  test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationUserRepositoryTests.cs
Labels: feature-flag

#5096 [PM-15628] 🎨Update docker reference link
  util/Setup/Templates/DockerCompose.hbs
Labels: community-pr

#5114 [PM-12443] add feature flag
  src/Core/Constants.cs
Labels: feature-flag

#5139 [PM-14245] Remove policy definitions feature flag
  src/Core/Constants.cs
Labels: feature-flag

#5118 [PM-15128] Add Promote Provider Service User functionality to Bitwarden Portal
  src/Admin/Controllers/ToolsController.cs
  src/Admin/Enums/Permissions.cs
  src/Admin/Models/PromoteProviderServiceUserModel.cs
  src/Admin/Utilities/RolePermissionMapping.cs
  src/Admin/Views/Shared/_Layout.cshtml
  src/Admin/Views/Tools/PromoteProviderServiceUser.cshtml
  src/Core/Constants.cs
Labels: feature-flag

#5159 Add Authenticator sync flags
  src/Core/Constants.cs
Labels: feature-flag

#5158 [PM-15091] Removing access intelligence server side feature flag
  src/Core/Constants.cs
Labels: feature-flag

#5190 [PM-16225] Add app review prompt flag
  src/Core/Constants.cs
Labels: feature-flag

#5193 [PM-15814]Alert owners of reseller-managed orgs to renewal events
  src/Api/Billing/Models/Responses/OrganizationMetadataResponse.cs
  src/Core/Billing/Models/OrganizationMetadata.cs
  src/Core/Billing/Services/Implementations/OrganizationBillingService.cs
  src/Core/Constants.cs
  test/Api.Test/Billing/Controllers/OrganizationBillingControllerTests.cs
Labels: feature-flag
