Repository bitwarden/server, pull requests merged in 2024-06, with the labels that each got.

#4088 [PM-6794] block legacy users from authN
  src/Core/Constants.cs
  src/Core/Services/IUserService.cs
  src/Core/Services/Implementations/UserService.cs
  src/Identity/IdentityServer/BaseRequestValidator.cs
  src/Identity/IdentityServer/CustomTokenRequestValidator.cs
  test/Identity.IntegrationTest/Endpoints/IdentityServerTests.cs
Labels: feature-flag

#3403 [AC-1779] Add comment to clarify ExpirationWithoutGracePeriod in OrganizationLicense
  src/Core/Models/Business/OrganizationLicense.cs
Labels: needs-qa

#4177 [PM-8814] Add removed EU feature flag
  src/Core/Constants.cs
Labels: feature-flag

#4191 [PM-8792] BUG - Remove required annotation from AccessAll
  src/Api/AdminConsole/Models/Request/GroupRequestModel.cs
Labels: bug

#4229 [PM-7084] Add feature flag for 2FA component refactor
  src/Core/Constants.cs
Labels: feature-flag
