Repository bitwarden/server, pull requests merged in 2024-11, with the labels that each got.

#4860 [PM-11505] Delete the feature flag PM-5864-dollar-threshold
  src/Core/Constants.cs
  src/Core/Services/Implementations/StripePaymentService.cs
Labels: feature-flag

#4966 Removed eu-environment feature flag
  src/Core/Constants.cs
Labels: feature-flag

#4575 [PM-10394] Add new item type ssh key
  src/Api/Vault/Controllers/SyncController.cs
  src/Api/Vault/Models/CipherSSHKeyModel.cs
  src/Api/Vault/Models/Request/CipherRequestModel.cs
  src/Api/Vault/Models/Response/CipherResponseModel.cs
  src/Core/Constants.cs
  src/Core/Vault/Enums/CipherType.cs
  src/Core/Vault/Models/Data/CipherSSHKeyData.cs
Labels: feature-flag

#4982 [PM-14544] Update Duo migration for MariaDB Compatibility
  util/MySqlMigrations/HelperScripts/2024-09-05_00_SyncDuoVersionFourMetadataToVersionTwo.sql
Labels: community-pr

#4987 [PM-12273] Add Admin Console Integration Page Feature Flag
  src/Core/Constants.cs
Labels: feature-flag

#4959 [PM-12479] - Adding group-details endpoint
  src/Api/AdminConsole/Controllers/GroupsController.cs
  src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
  src/Api/Api.csproj
  src/Api/Utilities/ServiceCollectionExtensions.cs
  src/Api/Vault/AuthorizationHandlers/Groups/GroupAuthorizationHandler.cs
  src/Api/Vault/AuthorizationHandlers/Groups/GroupOperations.cs
  src/Core/AdminConsole/OrganizationFeatures/Groups/Authorization/GroupAuthorizationHandler.cs
  src/Core/AdminConsole/OrganizationFeatures/Groups/Authorization/GroupOperations.cs
  src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/Authorization/OrganizationUserUserDetailsAuthorizationHandler.cs
  src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/Authorization/OrganizationUserUserMiniDetailsAuthorizationHandler.cs
  src/Core/AdminConsole/OrganizationFeatures/Shared/Authorization/OrganizationScope.cs
  src/Core/Constants.cs
  test/Api.Test/AdminConsole/AuthorizationHandlers/GroupAuthorizationHandlerTests.cs
  test/Api.Test/Vault/AuthorizationHandlers/GroupAuthorizationHandlerTests.cs
  test/Core.Test/AdminConsole/Authorization/OrganizationUserUserDetailsAuthorizationHandlerTests.cs
  test/Core.Test/AdminConsole/Authorization/OrganizationUserUserMiniDetailsAuthorizationHandlerTests.cs
Labels: feature-flag

#4956 [PM-13868]Remove the flag for upgrade path dialog
  src/Core/Constants.cs
Labels: feature-flag

#5028 [PM-11798] Remove `enable-consolidated-billing` feature flag
  bitwarden_license/src/Commercial.Core/AdminConsole/Providers/CreateProviderCommand.cs
  bitwarden_license/src/Commercial.Core/AdminConsole/Providers/RemoveOrganizationFromProviderCommand.cs
  bitwarden_license/src/Commercial.Core/AdminConsole/Services/ProviderService.cs
  bitwarden_license/test/Commercial.Core.Test/AdminConsole/ProviderFeatures/RemoveOrganizationFromProviderCommandTests.cs
  bitwarden_license/test/Commercial.Core.Test/AdminConsole/Services/ProviderServiceTests.cs
  src/Admin/AdminConsole/Controllers/OrganizationsController.cs
  src/Admin/AdminConsole/Controllers/ProvidersController.cs
  src/Admin/AdminConsole/Views/Providers/CreateMsp.cshtml
  src/Admin/AdminConsole/Views/Providers/Edit.cshtml
  src/Api/AdminConsole/Controllers/OrganizationsController.cs
  src/Api/Billing/Controllers/BaseProviderController.cs
  src/Api/Billing/Controllers/ProviderBillingController.cs
  src/Api/Billing/Controllers/ProviderClientsController.cs
  src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
  src/Core/Billing/Extensions/BillingExtensions.cs
  src/Core/Constants.cs
  test/Admin.Test/AdminConsole/Controllers/OrganizationsControllerTests.cs
  test/Api.Test/AdminConsole/Controllers/OrganizationsControllerTests.cs
  test/Api.Test/Billing/Controllers/ProviderBillingControllerTests.cs
  test/Api.Test/Billing/Utilities.cs
  test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs
Labels: feature-flag

#5027 [PM-13346] Email notification impacts
  src/Api/Billing/Controllers/OrganizationSponsorshipsController.cs
  src/Core/AdminConsole/Enums/PolicyType.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyServiceCollectionExtensions.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/FreeFamiliesForEnterprisePolicyValidator.cs
  src/Core/Constants.cs
  src/Core/MailTemplates/Handlebars/FamiliesForEnterprise/FamiliesForEnterpriseRemovedFromFamilyUser.html.hbs
  src/Core/MailTemplates/Handlebars/FamiliesForEnterprise/FamiliesForEnterpriseRemovedFromFamilyUser.text.hbs
  src/Core/Models/Api/Response/OrganizationSponsorships/PreValidateSponsorshipResponseModel.cs
  src/Core/Models/Mail/FamiliesForEnterprise/FamiliesForEnterpriseRemoveOfferViewModel.cs
  src/Core/Services/IMailService.cs
  src/Core/Services/Implementations/HandlebarsMailService.cs
  src/Core/Services/NoopImplementations/NoopMailService.cs
  test/Core.Test/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/FreeFamiliesForEnterprisePolicyValidatorTests.cs
Labels: feature-flag

#5050 [PM-15069] Updated customer metadata when updating to use bank account
  src/Core/Billing/Services/Implementations/SubscriberService.cs
Labels: ephemeral-environment

#5005 [PM-12729] Add QA flag to circumvent minimum client version to retreive ssh key ciphers
  src/Api/Vault/Controllers/SyncController.cs
  src/Core/Constants.cs
Labels: feature-flag

#5076 [PM-12684] Remove deprecated feature flag for Members TwoFA query optimization
  src/Core/Constants.cs
Labels: feature-flag
