Repository bitwarden/server, pull requests merged in 2024-10, with the labels that each got.

#4836 [PM-11504]Remove FF for delete provider[AC-1218-delete-provide]
  src/Admin/AdminConsole/Views/Providers/Edit.cshtml
  src/Core/Constants.cs
Labels: feature-flag

#4846 [PM-10961] Cannot delete MSP with apostrophe in name
  src/Admin/AdminConsole/Controllers/ProvidersController.cs
  src/Admin/AdminConsole/Views/Providers/_ProviderScripts.cshtml
Labels: needs-qa

#4838 [PM-12358] New Verified Organization Domain SSO Detail endpoint
  src/Api/AdminConsole/Controllers/OrganizationDomainController.cs
  src/Api/AdminConsole/Models/Response/Organizations/VerifiedOrganizationDomainSsoDetailResponseModel.cs
  src/Api/AdminConsole/Models/Response/Organizations/VerifiedOrganizationDomainSsoDetailsResponseModel.cs
  src/Core/Constants.cs
  src/Core/Models/Data/Organizations/VerifiedOrganizationDomainSsoDetail.cs
  src/Core/Repositories/IOrganizationDomainRepository.cs
  src/Infrastructure.Dapper/Repositories/OrganizationDomainRepository.cs
  src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs
  src/Sql/dbo/Stored Procedures/VerfiedOrganaizationDomainSsoDetails_ReadByEmail.sql
  test/Api.Test/AdminConsole/Controllers/OrganizationDomainControllerTests.cs
  util/Migrator/DbScripts/2024-09-26_00_AddVerifiedOrganizationDomainSsoDetails_ReadByEmail.sql
Labels: feature-flag

#4812 [PM-12777] Fixed Issue #4034, API endpoint now handles optional parameters
  bitwarden_license/src/Scim/Controllers/v2/UsersController.cs
  bitwarden_license/src/Scim/Models/GetUserQueryParamModel.cs
  bitwarden_license/src/Scim/Users/GetUsersListQuery.cs
  bitwarden_license/src/Scim/Users/Interfaces/IGetUsersListQuery.cs
  bitwarden_license/test/Scim.IntegrationTest/Controllers/v2/UsersControllerTests.cs
  bitwarden_license/test/Scim.Test/Users/GetUsersListQueryTests.cs
Labels: community-pr

#4857 [PM-13213] Replace `${{ github.ref }}` with `GITHUB_REF` in build.yml scripts
  .github/workflows/build.yml
Labels: community-pr

#4730 Split `Organization.LimitCollectionCreationDeletion` into two separate business rules
  src/Admin/AdminConsole/Views/Organizations/_ViewInformation.cshtml
  src/Api/AdminConsole/Controllers/OrganizationsController.cs
  src/Api/AdminConsole/Models/Response/Organizations/OrganizationResponseModel.cs
  src/Api/AdminConsole/Models/Response/ProfileOrganizationResponseModel.cs
  src/Api/AdminConsole/Models/Response/ProfileProviderOrganizationResponseModel.cs
  src/Api/Models/Request/Organizations/OrganizationCollectionManagementUpdateRequestModel.cs
  src/Api/Vault/AuthorizationHandlers/Collections/BulkCollectionAuthorizationHandler.cs
  src/Core/AdminConsole/Entities/Organization.cs
  src/Core/AdminConsole/Models/Data/Organizations/OrganizationAbility.cs
  src/Core/AdminConsole/Models/Data/Organizations/OrganizationUsers/OrganizationUserOrganizationDetails.cs
  src/Core/AdminConsole/Models/Data/Organizations/SelfHostedOrganizationDetails.cs
  src/Core/AdminConsole/Models/Data/Provider/ProviderUserOrganizationDetails.cs
  src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
  src/Core/Constants.cs
  src/Core/Models/Business/OrganizationLicense.cs
  src/Core/OrganizationFeatures/OrganizationLicenses/UpdateOrganizationLicenseCommand.cs
  src/Infrastructure.EntityFramework/AdminConsole/Models/Organization.cs
  src/Infrastructure.EntityFramework/AdminConsole/Repositories/OrganizationRepository.cs
  src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/OrganizationUserOrganizationDetailsViewQuery.cs
  src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/ProviderUserOrganizationDetailsViewQuery.cs
  test/Api.Test/Vault/AuthorizationHandlers/BulkCollectionAuthorizationHandlerTests.cs
  test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationUserRepositoryTests.cs
Labels: feature-flag

#4877 [PM-13322] [BEEEP] Add PolicyValidators and refactor policy save logic
  src/Core/AdminConsole/Enums/PolicyType.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/IPolicyValidator.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/ISavePolicyCommand.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/Implementations/SavePolicyCommand.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/Models/PolicyUpdate.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyServiceCollectionExtensions.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/MaximumVaultTimeoutPolicyValidator.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/PolicyValidatorHelpers.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/RequireSsoPolicyValidator.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/ResetPasswordPolicyValidator.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/SingleOrgPolicyValidator.cs
  src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/TwoFactorAuthenticationPolicyValidator.cs
  src/Core/AdminConsole/Services/Implementations/PolicyService.cs
  src/Core/Constants.cs
  src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
  test/Common/AutoFixture/SutProvider.cs
  test/Common/AutoFixture/SutProviderExtensions.cs
  test/Common/Common.csproj
  test/Core.Test/AdminConsole/AutoFixture/PolicyFixtures.cs
  test/Core.Test/AdminConsole/AutoFixture/PolicyUpdateFixtures.cs
  test/Core.Test/AdminConsole/OrganizationFeatures/Policies/PolicyValidatorFixtures.cs
  test/Core.Test/AdminConsole/OrganizationFeatures/Policies/PolicyValidatorHelpersTests.cs
  test/Core.Test/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/RequireSsoPolicyValidatorTests.cs
  test/Core.Test/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/ResetPasswordPolicyValidatorTests.cs
  test/Core.Test/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/SingleOrgPolicyValidatorTests.cs
  test/Core.Test/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/TwoFactorAuthenticationPolicyValidatorTests.cs
  test/Core.Test/AdminConsole/OrganizationFeatures/Policies/SavePolicyCommandTests.cs
Labels: feature-flag

#4933 Add generator-tools-modernization feature flag
  src/Core/Constants.cs
Labels: feature-flag

#4930 [PM-13824] Remove bulk-device-approval feature flag definition
  src/Core/Constants.cs
Labels: feature-flag

#4931 [PM-13790] Remove RefactorOrganizationUserApi feature flag
  src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
  src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/Authorization/OrganizationUserUserDetailsAuthorizationHandler.cs
  src/Core/Constants.cs
  test/Core.Test/AdminConsole/Authorization/OrganizationUserUserDetailsAuthorizationHandlerTests.cs
Labels: feature-flag

#4944 [PM-8213] Feature flag for `new-device-verification`
  src/Core/Constants.cs
Labels: feature-flag
