Repository bitwarden/server, pull requests merged in 2024-09, with the labels that each got.

#4694 [PM-11619] Replace cipher encryption feature flag with server-side flag
  src/Core/Constants.cs
Labels: feature-flag

#4739 [PM-11705] Typo Update in OrganizationsController.cs
  src/Api/AdminConsole/Controllers/OrganizationsController.cs
Labels: community-pr

#4738 [PM-11661] Add Feature Flag For Storage Reseed Refactor
  src/Core/Constants.cs
Labels: feature-flag

#4743 [AC-3034] - Fixes the dupe issue on group and colletion
  src/Api/Tools/Models/Response/MemberAccessReportModel.cs
Labels: needs-qa

#4751 Fix incorrect links in welcome emails
  src/Core/MailTemplates/Handlebars/TrialInitiation.html.hbs
  src/Core/MailTemplates/Handlebars/TrialInitiation.text.hbs
  src/Core/MailTemplates/Handlebars/Welcome.html.hbs
  src/Core/MailTemplates/Handlebars/Welcome.text.hbs
Labels: bug

#4794 Remove key-rotation-improvements feature flag
  src/Core/Constants.cs
Labels: feature-flag

#4746 [PM-11602] Error toast when expired org attempts to auto scale is unclear
  src/Core/Services/Implementations/StripePaymentService.cs
Labels: needs-qa

#4705 [PM-5450] Add check for admin/org access for events
  src/Events/Controllers/CollectController.cs
Labels: needs-qa

#4752 [PM-3478] Refactor OrganizationUser api
  src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
  src/Api/AdminConsole/Models/Response/Organizations/OrganizationUserResponseModel.cs
  src/Api/Utilities/ServiceCollectionExtensions.cs
  src/Api/Vault/AuthorizationHandlers/OrganizationUsers/OrganizationUserAuthorizationHandler.cs
  src/Api/Vault/AuthorizationHandlers/OrganizationUsers/OrganizationUserOperations.cs
  src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/Authorization/OrganizationScope.cs
  src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/Authorization/OrganizationUserUserDetailsAuthorizationHandler.cs
  src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/Authorization/OrganizationUserUserDetailsOperations.cs
  src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/Authorization/OrganizationUserUserMiniDetailsAuthorizationHandler.cs
  src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/Authorization/OrganizationUserUserMiniDetailsOperations.cs
  src/Core/Constants.cs
  src/Core/OrganizationFeatures/OrganizationServiceCollectionExtensions.cs
  test/Api.Test/Vault/AuthorizationHandlers/OrganizationUserAuthorizationHandlerTests.cs
  test/Core.Test/AdminConsole/Authorization/OrganizationUserUserDetailsAuthorizationHandlerTests.cs
  test/Core.Test/AdminConsole/Authorization/OrganizationUserUserMiniDetailsAuthorizationHandlerTests.cs
  test/Core.Test/AdminConsole/AutoFixture/CurrentContextOrganizationFixtures.cs
Labels: feature-flag
