Repository bitwarden/server, pull requests merged in 2025-01, with the labels that each got.

#5081 chore: update `LastActivityDate` on installation token refresh
  src/Api/Platform/Installations/Controllers/InstallationsController.cs
  src/Core/Constants.cs
  src/Core/Platform/Installations/Commands/UpdateInstallationActivityDateCommand/IUpdateInstallationCommand.cs
  src/Core/Platform/Installations/Commands/UpdateInstallationActivityDateCommand/UpdateInstallationCommand.cs
  src/Core/Platform/Installations/Entities/Installation.cs
  src/Core/Platform/Installations/Queries/GetInstallationQuery/GetInstallationQuery.cs
  src/Core/Platform/Installations/Queries/GetInstallationQuery/IGetInstallationQuery.cs
  src/Core/Platform/PlatformServiceCollectionExtensions.cs
  src/Core/Platform/Push/Services/RelayPushRegistrationService.cs
  src/Identity/IdentityServer/RequestValidators/CustomTokenRequestValidator.cs
  src/Identity/IdentityServer/RequestValidators/WebAuthnGrantValidator.cs
  src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
  test/Core.Test/Platform/Installations/Commands/UpdateInstallationCommandTests.cs
Labels: feature-flag

#5163 [PM-15961] Remove FF: PM-14401-scale-msp-on-client-organization-update
  src/Admin/AdminConsole/Controllers/OrganizationsController.cs
  src/Core/Constants.cs
  test/Admin.Test/AdminConsole/Controllers/OrganizationsControllerTests.cs
Labels: feature-flag

#5209 [PM-16607] - Removed feature flag logic pm-3479-secure-org-group-details
  src/Api/AdminConsole/Controllers/GroupsController.cs
  src/Core/Constants.cs
Labels: feature-flag

#5234 [PM-16867] Add feature flag for Blocked Domains feature
  src/Core/Constants.cs
Labels: feature-flag

#5212 [PM-10648] Remove block legacy users feature flag
  src/Core/Constants.cs
  src/Identity/IdentityServer/RequestValidators/BaseRequestValidator.cs
  test/Identity.Test/IdentityServer/BaseRequestValidatorTests.cs
Labels: feature-flag

#5258 [PM-17014] Fix delete action for cs/billing | add RequestDelete permission
  src/Admin/AdminConsole/Views/Organizations/Edit.cshtml
  src/Admin/Enums/Permissions.cs
  src/Admin/Utilities/RolePermissionMapping.cs
Labels: bug

#5255 [PM-15193] Remove PromoteProviderServiceUserTool feature flag and checks from ToolsController and layout
  src/Admin/Controllers/ToolsController.cs
  src/Admin/Views/Shared/_Layout.cshtml
  src/Core/Constants.cs
Labels: feature-flag

#5263 [PM-15182] Remove remove-provider-export-permission feature flag
  src/Api/Tools/Controllers/OrganizationExportController.cs
  src/Core/Constants.cs
  src/Core/Context/ICurrentContext.cs
  src/Core/Services/ICollectionService.cs
  src/Core/Services/Implementations/CollectionService.cs
  src/Core/Vault/Services/ICipherService.cs
  src/Core/Vault/Services/Implementations/CipherService.cs
  test/Core.Test/Services/CollectionServiceTests.cs
Labels: feature-flag

#5282 [PM-17189] Remove feature flag "browser-fileless-import"
  src/Core/Constants.cs
Labels: feature-flag

#5284 [PM-15564] Provider clients components remove feature flag
  src/Core/Constants.cs
Labels: feature-flag

#5253 [PM-16982] Add argon2-default flag
  src/Core/Constants.cs
Labels: feature-flag

#5309 Group AC Team feature flags
  src/Core/Constants.cs
Labels: feature-flag

#5201 [PM-11730] Remove feature flag: AC-2476-deprecate-stripe-sources-api
  src/Api/Billing/Controllers/OrganizationBillingController.cs
  src/Core/AdminConsole/OrganizationFeatures/Organizations/CloudOrganizationSignUpCommand.cs
  src/Core/Constants.cs
  src/Core/OrganizationFeatures/OrganizationSubscriptions/UpgradeOrganizationPlanCommand.cs
  src/Core/Services/Implementations/UserService.cs
  test/Api.IntegrationTest/Helpers/OrganizationTestHelpers.cs
  test/Core.Test/AdminConsole/OrganizationFeatures/Organizations/OrganizationSignUp/CloudOrganizationSignUpCommandTests.cs
  test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpgradeOrganizationPlanCommandTests.cs
  test/IntegrationTestCommon/Factories/WebApplicationFactoryBase.cs
Labels: feature-flag

#5270 [PM-15637] Add Email Notification Templates and Logic for Device Approval Requests
  src/Core/AdminConsole/Models/Mail/DeviceApprovalRequestedViewModel.cs
  src/Core/Auth/Services/Implementations/AuthRequestService.cs
  src/Core/Constants.cs
  src/Core/MailTemplates/Handlebars/AdminConsole/NotifyAdminDeviceApprovalRequested.html.hbs
  src/Core/MailTemplates/Handlebars/AdminConsole/NotifyAdminDeviceApprovalRequested.text.hbs
  src/Core/MailTemplates/Handlebars/AdminConsole/SelfHostNotifyAdminDeviceApprovalRequested.html.hbs
  src/Core/MailTemplates/Handlebars/AdminConsole/SelfHostNotifyAdminDeviceApprovalRequested.text.hbs
  src/Core/Services/IMailService.cs
  src/Core/Services/Implementations/HandlebarsMailService.cs
  src/Core/Services/NoopImplementations/NoopMailService.cs
  test/Core.Test/Auth/Services/AuthRequestServiceTests.cs
Labels: feature-flag

#5210 [PM-16512] Enable Automatic Tax for all subscriptions
  src/Billing/Services/Implementations/UpcomingInvoiceHandler.cs
  src/Core/Billing/Services/Implementations/OrganizationBillingService.cs
  src/Core/Billing/Services/Implementations/PremiumUserBillingService.cs
  src/Core/Billing/Services/Implementations/SubscriberService.cs
  src/Core/Services/Implementations/StripePaymentService.cs
Labels: needs-qa

#5329 [PM-17120] add feature flag
  src/Core/Constants.cs
Labels: feature-flag

#5328 [PM-14560] Risk insights notification feature flag for server
  src/Core/Constants.cs
Labels: feature-flag

#5356 [PM-17214] Add LimitItemDeletion feature flag
  src/Core/Constants.cs
Labels: feature-flag
