Repository bitwarden/server, pull requests merged in 2025-03, with the labels that each got.

#5462 remove feature flag
  src/Core/Constants.cs
Labels: feature-flag

#5424 [PM-5872] Credit load intermittently fails
  src/Billing/Constants/BitPayInvoiceStatus.cs
  src/Billing/Constants/BitPayNotificationCode.cs
  src/Billing/Controllers/BitPayController.cs
Labels: needs-qa

#5410 [PM-7125] Remove extension-refresh feature flag
  src/Core/Constants.cs
Labels: feature-flag

#5494 [Vault] Organize Feature Flags
  src/Core/Constants.cs
Labels: feature-flag

#5497 [PM-19155] Create feature Flag for Archive Vault Items
  src/Core/Constants.cs
Labels: feature-flag

#5511 [PM-19279] Add prelogin response
  src/Api/Auth/Controllers/AccountsController.cs
  src/Identity/Controllers/AccountsController.cs
  src/Identity/Models/Response/Accounts/PreloginResponseModel.cs
  src/Infrastructure.EntityFramework/Auth/Repositories/OpaqueKeyExchangeCredentialRepository.cs
  src/Infrastructure.EntityFramework/EntityFrameworkServiceCollectionExtensions.cs
  src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
  src/Sql/Auth/dbo/Stored Procedures/OpaqueKeyExchangeCredential_Create.sql
  src/Sql/Auth/dbo/Stored Procedures/OpaqueKeyExchangeCredential_DeleteById.sql
  src/Sql/dbo/Stored Procedures/User_DeleteById.sql
  test/Api.Test/Auth/Controllers/AccountsControllerTests.cs
  test/Core.Test/Services/UserServiceTests.cs
  test/Identity.Test/Controllers/AccountsControllerTests.cs
  util/Migrator/DbScripts/2025-03-12_00_CreateOpaqueKeyExchangeCredential.sql
Labels: DB-migrations-changed

#5527 [PM-17647] Add set/change password feature flags
  src/Core/Constants.cs
Labels: feature-flag

#5532 Wrapped phishing detection feature behind feature flag
  src/Api/Controllers/PhishingDomainsController.cs
  src/Api/Jobs/UpdatePhishingDomainsJob.cs
  src/Core/Constants.cs
Labels: feature-flag

#5541 feat : matching request email to session email
  src/Identity/IdentityServer/RequestValidators/AuthRequestHeaderValidator.cs
  src/Identity/IdentityServer/RequestValidators/IAuthRequestHeaderValidator.cs
  src/Identity/IdentityServer/RequestValidators/OpaqueKeyExchangeGrantValidator.cs
  src/Identity/IdentityServer/RequestValidators/ResourceOwnerPasswordValidator.cs
  src/Identity/Utilities/ServiceCollectionExtensions.cs
  src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
  src/Sql/Auth/dbo/Tables/OpaqueKeyExchangeCredential.sql
  test/Identity.IntegrationTest/openid-configuration.json
  util/Migrator/DbScripts/2025-03-20_00_CreateOpaqueKeyExchangeCredential.sql
Labels: DB-migrations-changed

#5204 [PM-16603] Add userkey rotation v2
  src/Api/Auth/Controllers/AccountsController.cs
  src/Api/Auth/Models/Request/Accounts/MasterPasswordUnlockDataModel.cs
  src/Api/KeyManagement/Controllers/AccountsKeyManagementController.cs
  src/Api/KeyManagement/Models/Requests/AccountKeysRequestModel.cs
  src/Api/KeyManagement/Models/Requests/RotateAccountKeysAndDataRequestModel.cs
  src/Api/KeyManagement/Models/Requests/UnlockDataRequestModel.cs
  src/Api/KeyManagement/Models/Requests/UserDataRequestModel.cs
  src/Core/Auth/UserFeatures/UserServiceCollectionExtensions.cs
  src/Core/Constants.cs
  src/Core/KeyManagement/Models/Data/MasterPasswordUnlockData.cs
  src/Core/KeyManagement/Models/Data/RotateUserAccountKeysData.cs
  src/Core/KeyManagement/UserKey/IRotateUserAccountKeysCommand.cs
  src/Core/KeyManagement/UserKey/Implementations/RotateUserAccountkeysCommand.cs
  src/Core/Repositories/IUserRepository.cs
  src/Infrastructure.Dapper/Repositories/UserRepository.cs
  src/Infrastructure.EntityFramework/Repositories/UserRepository.cs
  test/Api.IntegrationTest/KeyManagement/Controllers/AccountsKeyManagementControllerTests.cs
  test/Api.Test/KeyManagement/Controllers/AccountsKeyManagementControllerTests.cs
  test/Api.Test/KeyManagement/Models/Request/MasterPasswordUnlockDataModel.cs
  test/Core.Test/KeyManagement/UserKey/RotateUserAccountKeysCommandTests.cs
  test/Core.Test/KeyManagement/UserKey/RotateUserKeyCommandTests.cs
  test/Infrastructure.EFIntegration.Test/Repositories/UserRepositoryTests.cs
Labels: feature-flag

#5557 Sort km feature flags
  src/Core/Constants.cs
Labels: feature-flag

#5551 [PM-17558] Remove ShortcutDuplicatePatchRequests feature flag
  bitwarden_license/src/Scim/Controllers/v2/GroupsController.cs
  bitwarden_license/src/Scim/Groups/Interfaces/IPatchGroupCommand.cs
  bitwarden_license/src/Scim/Groups/Interfaces/IPatchGroupCommandvNext.cs
  bitwarden_license/src/Scim/Groups/PatchGroupCommand.cs
  bitwarden_license/src/Scim/Groups/PatchGroupCommandvNext.cs
  bitwarden_license/src/Scim/Utilities/ScimServiceCollectionExtensions.cs
  bitwarden_license/test/Scim.IntegrationTest/Controllers/v2/GroupsControllerPatchTests.cs
  bitwarden_license/test/Scim.IntegrationTest/Controllers/v2/GroupsControllerPatchTestsvNext.cs
  bitwarden_license/test/Scim.Test/Groups/PatchGroupCommandTests.cs
  bitwarden_license/test/Scim.Test/Groups/PatchGroupCommandvNextTests.cs
  src/Core/Constants.cs
Labels: feature-flag

#5559 [PM-18523] Add SSO external ID visibility feature flag
  src/Core/Constants.cs
Labels: feature-flag

#5574 Complete feature flag grouping by team
  src/Core/Constants.cs
Labels: feature-flag
